name: GMLint
on:
  pull_request_target:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify Code
        id: verify-code
        run: |
          RESULT=$(./scripts/gmlint/gmlint)
          echo "$RESULT"
          MESSAGE_RESULT="$RESULT"
          MESSAGE_RESULT="${MESSAGE_RESULT//'%'/'%25'}"
          MESSAGE_RESULT="${MESSAGE_RESULT//$'\n'/'%0A'}"
          MESSAGE_RESULT="${MESSAGE_RESULT//$'\r'/'%0D'}"
          echo "::set-output name=result::$MESSAGE_RESULT"
          OUT="comment-message.md"
          if [ -z "$RESULT" ]; then
            echo "Everything looks good!" > $OUT
          else
            echo "Your code smells, and here and some reasons why:" > $OUT
            echo '```' >> $OUT
            echo "$RESULT" >> $OUT
            echo '```' >> $OUT
          fi
          MESSAGE="$(cat $OUT)"
          MESSAGE="${MESSAGE//'%'/'%25'}"
          MESSAGE="${MESSAGE//$'\n'/'%0A'}"
          MESSAGE="${MESSAGE//$'\r'/'%0D'}"
          echo "::set-output name=message::$MESSAGE"
      - name: Comment on PR
        uses: NejcZdovc/comment-pr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            ${{ steps.verify-code.outputs.message }}
      - name: Fail Workflow
        run: |
          RESULT="${{ steps.verify-code.outputs.result }}"
          echo "$RESULT"
          if [ -z "$RESULT" ]; then
            echo "Test passed!"
          else
            echo "Test failed!"
            exit 1
          fi
