name: GMLint
on:
  pull_request:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify Code
        id: verify-code
        run: |
          RESULT=$(./scripts/gmlint/gmlint)
          echo "--- test results ---"
          echo "$RESULT"
          echo "--- end results ---"
          MESSAGE=$(
            if [ -z "$RESULT" ]; then
              echo "Everything looks good!"
            else
              echo "Your code smells, and here and some reasons why:"
              echo '```'
              echo "$RESULT"
              echo '```'
            fi
          )
          echo "::set-output name=result::$MESSAGE"
      - name: Comment on PR
        uses: NejcZdovc/comment-pr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: "${{ steps.verify-code.outputs.result }}"
          indentifier: "GITHUB_COMMENT_RESULT"
      - name: Fail Workflow
        run: |
          if [ -z "$RESULT" ]; then
            echo "Test passed!"
          else
            echo "Test failed!"
            exit 1
          fi

