name: GMLint
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify Code
        run: |
          RESULT=$(./scripts/gmlint/gmlint)
          echo "--- test results ---"
          echo "$RESULT"
          echo "--- end results ---"
          mkdir -p output/
          if [ -z "$RESULT" ]; then
            echo "Everything looks good!" > output/results.txt
          else
            echo "Your code smells, and here and some reasons why:" > output/results.txt
            echo '```sh' >> output/results.txt
            echo "RESULT" >> output/results.txt
            echo '```' >> output/results.txt
          fi
      - uses: actions/upload-artifact@v1
        with:
          name: results
          path: output
      - uses: actions/download-artifact@v1
        with:
          name: results
      - name: Comment on PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: results/results.txt
      - name: Fail Workflow
        run: |
          RESULT=$(cat output/results.txt)
          if [ -z "$RESULT" ]; then
            echo "Test passed!"
          else
            echo "Test failed!"
            exit 1
          fi

